language: c

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      compiler: clang
    - os: linux
      dist: trusty
      compiler: gcc

addons:
  apt:
    packages:
      - clang

compiler:
  - gcc
  - clang

before_install:
  - $CC --version
  - which $CC

  - export CC=`which $CC`

  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get update --quiet --assume-yes; fi

  - sudo apt-get install splint --quiet --assume-yes
  - apt-get install clang-format-6.0 --quiet --assume-yes

script:
  - make all-checks

