language: c

sudo: required

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      compiler: clang
    - os: linux
      dist: trusty
      compiler: gcc

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang

compiler:
  - gcc
  - clang

before_install:
  - $CC --version
  - which $CC

  - export CC=`which $CC`

  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get update --quiet --assume-yes; fi

  - sudo apt-get install splint --quiet --assume-yes
  - sudo apt-get install clang-format --quiet --assume-yes

script:
  - make all-checks

